"""initial

Revision ID: 910fe74a5346
Revises: 
Create Date: 2026-03-24 21:16:20.486957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '910fe74a5346'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_user_email'), 'app_user', ['email'], unique=True)
    op.create_table('sandbox',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('owner_user_id', sa.String(), nullable=False),
    sa.Column('canvas_state', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sandbox_name'), 'sandbox', ['name'], unique=False)
    op.create_index(op.f('ix_sandbox_owner_user_id'), 'sandbox', ['owner_user_id'], unique=False)
    op.create_table('runrecord',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('sandbox_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('prompt', sa.String(), nullable=False),
    sa.Column('collector_output', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sandbox_id'], ['sandbox.id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index(op.f('ix_runrecord_sandbox_id'), 'runrecord', ['sandbox_id'], unique=False)
    op.create_table('sandboxedge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sandbox_id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['sandbox_id'], ['sandbox.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sandboxedge_sandbox_id'), 'sandboxedge', ['sandbox_id'], unique=False)
    op.create_index(op.f('ix_sandboxedge_source_id'), 'sandboxedge', ['source_id'], unique=False)
    op.create_index(op.f('ix_sandboxedge_target_id'), 'sandboxedge', ['target_id'], unique=False)
    op.create_table('sandboxnode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sandbox_id', sa.String(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['sandbox_id'], ['sandbox.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sandbox_id', 'node_id', name='uq_sandboxnode_sandbox_node')
    )
    op.create_index(op.f('ix_sandboxnode_kind'), 'sandboxnode', ['kind'], unique=False)
    op.create_index(op.f('ix_sandboxnode_sandbox_id'), 'sandboxnode', ['sandbox_id'], unique=False)
    op.create_table('runnodeoutput',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('output', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runrecord.run_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'node_id', name='uq_run_node_output')
    )
    op.create_index(op.f('ix_runnodeoutput_run_id'), 'runnodeoutput', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_runnodeoutput_run_id'), table_name='runnodeoutput')
    op.drop_table('runnodeoutput')
    op.drop_index(op.f('ix_sandboxnode_sandbox_id'), table_name='sandboxnode')
    op.drop_index(op.f('ix_sandboxnode_kind'), table_name='sandboxnode')
    op.drop_table('sandboxnode')
    op.drop_index(op.f('ix_sandboxedge_target_id'), table_name='sandboxedge')
    op.drop_index(op.f('ix_sandboxedge_source_id'), table_name='sandboxedge')
    op.drop_index(op.f('ix_sandboxedge_sandbox_id'), table_name='sandboxedge')
    op.drop_table('sandboxedge')
    op.drop_index(op.f('ix_runrecord_sandbox_id'), table_name='runrecord')
    op.drop_table('runrecord')
    op.drop_index(op.f('ix_sandbox_owner_user_id'), table_name='sandbox')
    op.drop_index(op.f('ix_sandbox_name'), table_name='sandbox')
    op.drop_table('sandbox')
    op.drop_index(op.f('ix_app_user_email'), table_name='app_user')
    op.drop_table('app_user')
    # ### end Alembic commands ###
